[package]
name = "hello-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = "0.7.6"
cortex-m-rt = "0.7.1"
embedded-hal = "0.2"
panic-halt = "0.2.0"
rtt-target = { version = "0.3.0", features = ["cortex-m"] }
stm32f4xx-hal = { version = "0.13.2", features = ["stm32f429"] }
