[build]
target = "thumbv7em-none-eabihf" # Cortex-M4F and Cortex-M7F (with FPU)

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = 'probe-run --chip STM32F429ZITx'

rustflags = [
  # Use LLD as the default linker
  "-C", "link-arg=-Tlink.x",
  # Warnings as erros
  "-D", "warnings"
]
