name: examples

on: [pull_request]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: thumbv7em-none-eabihf
        override: true
    - name: Prologue
      run: cargo update
    - name: Release
      run: | 
        cargo build --examples --features="panic" --release --verbose
    - name: Debug
      run: | 
        cargo build --examples --features="panic" --verbose
        